name: PoloCloud-Signs
version: 1.0
author: iPommes
main: de.polocloud.signs.bootstraps.PluginBootstrap

depend:
    - PoloCloud-Plugin
commands:
    cloudsigns:
        aliases:
            - sign
            - signs
            - cloudsign
        description: Command for managing the Signs for the PoloCloud
