name: PoloCloudSings
version: 1.0
authors:
    - PoloCloud
    - iPommes
main: de.polocloud.signs.bootstraps.PluginBootstrap

depend:
    - PoloCloud-Plugin
commands:
    cloudsigns:
        description: Command for managing the Signs for the PoloCloud
